apiVersion: v1
kind: Pod
metadata:
  name: integer-to-roman-pod
  labels:
    component: api
spec:
  containers:
    - name: integer-to-roman
      image: vmbarbosa/golang:pruebatecnica-vmbarbosa-dev
      imagePullPolicy: "Always"
      ports:
        - containerPort: 3000
