name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Dependencies Go
      run: |
          go get -u github.com/gorilla/mux

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v1

    - name: Login to docker hub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PASSWORD_DH }}  

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        file: Dockerfile

